AWSTemplateFormatVersion: 2010-09-09

Parameters:
  
  BranchName:
    Type: String

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jira-manager-webapp.viadev.io
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub access-identity-${Bucket}

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !Sub ${OriginAccessIdentity.S3CanonicalUserId}
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${Bucket}/*'

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: True
        Aliases:
          - !Ref Bucket
        ViewerCertificate:
          AcmCertificateArn: !ImportValue certification-viadevio
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only
        Origins:
          - Id: S3Origin
            DomainName: !Sub ${Bucket.DomainName}
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: False
        HttpVersion: http2
        DefaultRootObject: index.html
        PriceClass: PriceClass_100

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue hostedzoneid-viadevio
      Name: !Ref Bucket
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # Fix for Static Web Site on S3
        DNSName: !Sub ${Distribution.DomainName}

Outputs:

  BucketName:
    Value: !Ref Bucket

  CloudFrontDistributionId:
    Value: !Ref Distribution
